name: bmcsapps
channels:
- conda-forge
dependencies:
- appmode
- rise
- jupyter_contrib_nbextensions
- traits
- matplotlib
- numpy
- sympy
- scipy
- ipywidgets
- rise
- traitsui
- pyqt
- pyface
- mayavi
- pip
- pip:
  - bmcs


